export const teamLogoAssetPaths = [
  "/logos/Austria - Bundesliga/Austria Vienna.png",
  "/logos/Austria - Bundesliga/Grazer AK 1902.png",
  "/logos/Austria - Bundesliga/LASK.png",
  "/logos/Austria - Bundesliga/Rapid Vienna.png",
  "/logos/Austria - Bundesliga/Red Bull Salzburg.png",
  "/logos/Austria - Bundesliga/SC Austria Lustenau.png",
  "/logos/Austria - Bundesliga/SCR Altach.png",
  "/logos/Austria - Bundesliga/SK Sturm Graz.png",
  "/logos/Austria - Bundesliga/SV Ried.png",
  "/logos/Austria - Bundesliga/TSV Hartberg.png",
  "/logos/Austria - Bundesliga/Wolfsberger AC.png",
  "/logos/Austria - Bundesliga/WSG Tirol.png",
  "/logos/Belgium - Jupiler Pro League/Cercle Brugge.png",
  "/logos/Belgium - Jupiler Pro League/Club Brugge KV.png",
  "/logos/Belgium - Jupiler Pro League/KAA Gent.png",
  "/logos/Belgium - Jupiler Pro League/KRC Genk.png",
  "/logos/Belgium - Jupiler Pro League/KV Kortrijk.png",
  "/logos/Belgium - Jupiler Pro League/KV Mechelen.png",
  "/logos/Belgium - Jupiler Pro League/KVC Westerlo.png",
  "/logos/Belgium - Jupiler Pro League/Lommel SK.png",
  "/logos/Belgium - Jupiler Pro League/Oud-Heverlee Leuven.png",
  "/logos/Belgium - Jupiler Pro League/RAAL La Louvière.png",
  "/logos/Belgium - Jupiler Pro League/Royal Antwerp FC.png",
  "/logos/Belgium - Jupiler Pro League/Royal Charleroi SC.png",
  "/logos/Belgium - Jupiler Pro League/RSC Anderlecht.png",
  "/logos/Belgium - Jupiler Pro League/Sint-Truidense VV.png",
  "/logos/Belgium - Jupiler Pro League/SK Beveren.png",
  "/logos/Belgium - Jupiler Pro League/Standard Liège.png",
  "/logos/Belgium - Jupiler Pro League/Union Saint-Gilloise.png",
  "/logos/Belgium - Jupiler Pro League/Zulte Waregem.png",
  "/logos/Bulgaria - efbet Liga/Arda Kardzhali.png",
  "/logos/Bulgaria - efbet Liga/Botev Plovdiv.png",
  "/logos/Bulgaria - efbet Liga/Botev Vratsa.png",
  "/logos/Bulgaria - efbet Liga/Cherno More Varna.png",
  "/logos/Bulgaria - efbet Liga/CSKA 1948.png",
  "/logos/Bulgaria - efbet Liga/CSKA Sofia.png",
  "/logos/Bulgaria - efbet Liga/Dunav Ruse.png",
  "/logos/Bulgaria - efbet Liga/Levski Sofia.png",
  "/logos/Bulgaria - efbet Liga/Lokomotiv Plovdiv.png",
  "/logos/Bulgaria - efbet Liga/Lokomotiv Sofia.png",
  "/logos/Bulgaria - efbet Liga/Ludogorets Razgrad.png",
  "/logos/Bulgaria - efbet Liga/Septemvri Sofia.png",
  "/logos/Bulgaria - efbet Liga/Slavia Sofia.png",
  "/logos/Bulgaria - efbet Liga/Spartak Varna.png",
  "/logos/Croatia - SuperSport HNL/GNK Dinamo Zagreb.png",
  "/logos/Croatia - SuperSport HNL/HNK Gorica.png",
  "/logos/Croatia - SuperSport HNL/HNK Hajduk Split.png",
  "/logos/Croatia - SuperSport HNL/HNK Rijeka.png",
  "/logos/Croatia - SuperSport HNL/NK Istra 1961.png",
  "/logos/Croatia - SuperSport HNL/NK Lokomotiva Zagreb.png",
  "/logos/Croatia - SuperSport HNL/NK Osijek.png",
  "/logos/Croatia - SuperSport HNL/NK Rudes.png",
  "/logos/Croatia - SuperSport HNL/NK Varazdin.png",
  "/logos/Croatia - SuperSport HNL/Slaven Belupo Koprivnica.png",
  "/logos/Czech Republic - Chance Liga/1.FC Slovacko.png",
  "/logos/Czech Republic - Chance Liga/AC Sparta Prague.png",
  "/logos/Czech Republic - Chance Liga/Bohemians Prague 1905.png",
  "/logos/Czech Republic - Chance Liga/FC Banik Ostrava.png",
  "/logos/Czech Republic - Chance Liga/FC Hradec Kralove.png",
  "/logos/Czech Republic - Chance Liga/FC Slovan Liberec.png",
  "/logos/Czech Republic - Chance Liga/FC Viktoria Plzen.png",
  "/logos/Czech Republic - Chance Liga/FC Zbrojovka Brno.png",
  "/logos/Czech Republic - Chance Liga/FC Zlin.png",
  "/logos/Czech Republic - Chance Liga/FK Jablonec.png",
  "/logos/Czech Republic - Chance Liga/FK Mlada Boleslav.png",
  "/logos/Czech Republic - Chance Liga/FK Pardubice.png",
  "/logos/Czech Republic - Chance Liga/FK Teplice.png",
  "/logos/Czech Republic - Chance Liga/SK Artis Brno.png",
  "/logos/Czech Republic - Chance Liga/SK Sigma Olomouc.png",
  "/logos/Czech Republic - Chance Liga/SK Slavia Prague.png",
  "/logos/Denmark - Superliga/Aarhus GF.png",
  "/logos/Denmark - Superliga/AC Horsens.png",
  "/logos/Denmark - Superliga/Bröndby IF.png",
  "/logos/Denmark - Superliga/FC Copenhagen.png",
  "/logos/Denmark - Superliga/FC Midtjylland.png",
  "/logos/Denmark - Superliga/FC Nordsjaelland.png",
  "/logos/Denmark - Superliga/Lyngby Boldklub.png",
  "/logos/Denmark - Superliga/Odense Boldklub.png",
  "/logos/Denmark - Superliga/Randers FC.png",
  "/logos/Denmark - Superliga/Silkeborg IF.png",
  "/logos/Denmark - Superliga/Sönderjyske Fodbold.png",
  "/logos/Denmark - Superliga/Viborg FF.png",
  "/logos/England - Premier League/AFC Bournemouth.png",
  "/logos/England - Premier League/Arsenal FC.png",
  "/logos/England - Premier League/Aston Villa.png",
  "/logos/England - Premier League/Brentford FC.png",
  "/logos/England - Premier League/Brighton & Hove Albion.png",
  "/logos/England - Premier League/Chelsea FC.png",
  "/logos/England - Premier League/Coventry City.png",
  "/logos/England - Premier League/Crystal Palace.png",
  "/logos/England - Premier League/Everton FC.png",
  "/logos/England - Premier League/Fulham FC.png",
  "/logos/England - Premier League/Hull City.png",
  "/logos/England - Premier League/Ipswich Town.png",
  "/logos/England - Premier League/Leeds United.png",
  "/logos/England - Premier League/Liverpool FC.png",
  "/logos/England - Premier League/Manchester City.png",
  "/logos/England - Premier League/Manchester United.png",
  "/logos/England - Premier League/Newcastle United.png",
  "/logos/England - Premier League/Nottingham Forest.png",
  "/logos/England - Premier League/Sunderland AFC.png",
  "/logos/England - Premier League/Tottenham Hotspur.png",
  "/logos/France - Ligue 1/AJ Auxerre.png",
  "/logos/France - Ligue 1/Angers SCO.png",
  "/logos/France - Ligue 1/AS Monaco.png",
  "/logos/France - Ligue 1/ESTAC Troyes.png",
  "/logos/France - Ligue 1/FC Lorient.png",
  "/logos/France - Ligue 1/FC Toulouse.png",
  "/logos/France - Ligue 1/Le Havre AC.png",
  "/logos/France - Ligue 1/Le Mans FC.png",
  "/logos/France - Ligue 1/LOSC Lille.png",
  "/logos/France - Ligue 1/OGC Nice.png",
  "/logos/France - Ligue 1/Olympique Lyon.png",
  "/logos/France - Ligue 1/Olympique Marseille.png",
  "/logos/France - Ligue 1/Paris FC.png",
  "/logos/France - Ligue 1/Paris Saint-Germain.png",
  "/logos/France - Ligue 1/RC Lens.png",
  "/logos/France - Ligue 1/RC Strasbourg Alsace.png",
  "/logos/France - Ligue 1/Stade Brestois 29.png",
  "/logos/France - Ligue 1/Stade Rennais FC.png",
  "/logos/Germany - Bundesliga/1.FC Köln.png",
  "/logos/Germany - Bundesliga/1.FC Union Berlin.png",
  "/logos/Germany - Bundesliga/1.FSV Mainz 05.png",
  "/logos/Germany - Bundesliga/Bayer 04 Leverkusen.png",
  "/logos/Germany - Bundesliga/Bayern Munich.png",
  "/logos/Germany - Bundesliga/Borussia Dortmund.png",
  "/logos/Germany - Bundesliga/Borussia Mönchengladbach.png",
  "/logos/Germany - Bundesliga/Eintracht Frankfurt.png",
  "/logos/Germany - Bundesliga/FC Augsburg.png",
  "/logos/Germany - Bundesliga/FC Schalke 04.png",
  "/logos/Germany - Bundesliga/Hamburger SV.png",
  "/logos/Germany - Bundesliga/RB Leipzig.png",
  "/logos/Germany - Bundesliga/SC Freiburg.png",
  "/logos/Germany - Bundesliga/SC Paderborn 07.png",
  "/logos/Germany - Bundesliga/SV 07 Elversberg.png",
  "/logos/Germany - Bundesliga/SV Werder Bremen.png",
  "/logos/Germany - Bundesliga/TSG 1899 Hoffenheim.png",
  "/logos/Germany - Bundesliga/VfB Stuttgart.png",
  "/logos/Greece - Super League 1/AE Kifisia.png",
  "/logos/Greece - Super League 1/AEK Athens.png",
  "/logos/Greece - Super League 1/Aris Thessaloniki.png",
  "/logos/Greece - Super League 1/Asteras Aktor.png",
  "/logos/Greece - Super League 1/Atromitos Athens.png",
  "/logos/Greece - Super League 1/Iraklis Thessaloniki.png",
  "/logos/Greece - Super League 1/Kalamata FC.png",
  "/logos/Greece - Super League 1/Levadiakos.png",
  "/logos/Greece - Super League 1/OFI Crete.png",
  "/logos/Greece - Super League 1/Olympiacos Piraeus.png",
  "/logos/Greece - Super League 1/Panathinaikos.png",
  "/logos/Greece - Super League 1/Panetolikos.png",
  "/logos/Greece - Super League 1/PAOK Thessaloniki.png",
  "/logos/Greece - Super League 1/Volos NFC.png",
  "/logos/Israel - Ligat ha'Al/Beitar Jerusalem.png",
  "/logos/Israel - Ligat ha'Al/Hapoel Beer Sheva.png",
  "/logos/Israel - Ligat ha'Al/Hapoel Haifa.png",
  "/logos/Israel - Ligat ha'Al/Hapoel Jerusalem.png",
  "/logos/Israel - Ligat ha'Al/Hapoel Petah Tikva.png",
  "/logos/Israel - Ligat ha'Al/Hapoel Ramat Gan.png",
  "/logos/Israel - Ligat ha'Al/Hapoel Tel Aviv.png",
  "/logos/Israel - Ligat ha'Al/Ihud Bnei Sakhnin.png",
  "/logos/Israel - Ligat ha'Al/Ironi Kiryat Shmona.png",
  "/logos/Israel - Ligat ha'Al/Ironi Tiberias.png",
  "/logos/Israel - Ligat ha'Al/Maccabi Haifa.png",
  "/logos/Israel - Ligat ha'Al/Maccabi Netanya.png",
  "/logos/Israel - Ligat ha'Al/Maccabi Petah Tikva.png",
  "/logos/Israel - Ligat ha'Al/Maccabi Tel Aviv.png",
  "/logos/Italy - Serie A/AC Milan.png",
  "/logos/Italy - Serie A/AC Monza.png",
  "/logos/Italy - Serie A/ACF Fiorentina.png",
  "/logos/Italy - Serie A/AS Roma.png",
  "/logos/Italy - Serie A/Atalanta BC.png",
  "/logos/Italy - Serie A/Bologna FC 1909.png",
  "/logos/Italy - Serie A/Cagliari Calcio.png",
  "/logos/Italy - Serie A/Como 1907.png",
  "/logos/Italy - Serie A/Frosinone Calcio.png",
  "/logos/Italy - Serie A/Genoa CFC.png",
  "/logos/Italy - Serie A/Inter Milan.png",
  "/logos/Italy - Serie A/Juventus FC.png",
  "/logos/Italy - Serie A/Parma Calcio 1913.png",
  "/logos/Italy - Serie A/SS Lazio.png",
  "/logos/Italy - Serie A/SSC Napoli.png",
  "/logos/Italy - Serie A/Torino FC.png",
  "/logos/Italy - Serie A/Udinese Calcio.png",
  "/logos/Italy - Serie A/US Lecce.png",
  "/logos/Italy - Serie A/US Sassuolo.png",
  "/logos/Italy - Serie A/Venezia FC.png",
  "/logos/Netherlands - Eredivisie/ADO Den Haag.png",
  "/logos/Netherlands - Eredivisie/Ajax Amsterdam.png",
  "/logos/Netherlands - Eredivisie/AZ Alkmaar.png",
  "/logos/Netherlands - Eredivisie/Excelsior Rotterdam.png",
  "/logos/Netherlands - Eredivisie/FC Groningen.png",
  "/logos/Netherlands - Eredivisie/FC Twente Enschede.png",
  "/logos/Netherlands - Eredivisie/FC Utrecht.png",
  "/logos/Netherlands - Eredivisie/Feyenoord Rotterdam.png",
  "/logos/Netherlands - Eredivisie/Fortuna Sittard.png",
  "/logos/Netherlands - Eredivisie/Go Ahead Eagles.png",
  "/logos/Netherlands - Eredivisie/NEC Nijmegen.png",
  "/logos/Netherlands - Eredivisie/PEC Zwolle.png",
  "/logos/Netherlands - Eredivisie/PSV Eindhoven.png",
  "/logos/Netherlands - Eredivisie/SC Cambuur Leeuwarden.png",
  "/logos/Netherlands - Eredivisie/SC Heerenveen.png",
  "/logos/Netherlands - Eredivisie/SC Telstar.png",
  "/logos/Netherlands - Eredivisie/Sparta Rotterdam.png",
  "/logos/Netherlands - Eredivisie/Willem II Tilburg.png",
  "/logos/Norway - Eliteserien/Aalesunds FK.png",
  "/logos/Norway - Eliteserien/FK BodøGlimt.png",
  "/logos/Norway - Eliteserien/Fredrikstad FK.png",
  "/logos/Norway - Eliteserien/Hamarkameratene.png",
  "/logos/Norway - Eliteserien/IK Start.png",
  "/logos/Norway - Eliteserien/KFUM-Kameratene Oslo.png",
  "/logos/Norway - Eliteserien/Kristiansund BK.png",
  "/logos/Norway - Eliteserien/Lillestrøm SK.png",
  "/logos/Norway - Eliteserien/Molde FK.png",
  "/logos/Norway - Eliteserien/Rosenborg BK.png",
  "/logos/Norway - Eliteserien/Sandefjord Fotball.png",
  "/logos/Norway - Eliteserien/Sarpsborg 08 FF.png",
  "/logos/Norway - Eliteserien/SK Brann.png",
  "/logos/Norway - Eliteserien/Tromsø IL.png",
  "/logos/Norway - Eliteserien/Vålerenga Fotball Elite.png",
  "/logos/Norway - Eliteserien/Viking FK.png",
  "/logos/Poland - PKO BP Ekstraklasa/Cracovia.png",
  "/logos/Poland - PKO BP Ekstraklasa/GKS Katowice.png",
  "/logos/Poland - PKO BP Ekstraklasa/Górnik Zabrze.png",
  "/logos/Poland - PKO BP Ekstraklasa/Jagiellonia Bialystok.png",
  "/logos/Poland - PKO BP Ekstraklasa/Korona Kielce.png",
  "/logos/Poland - PKO BP Ekstraklasa/Lech Poznan.png",
  "/logos/Poland - PKO BP Ekstraklasa/Legia Warszawa.png",
  "/logos/Poland - PKO BP Ekstraklasa/Motor Lublin.png",
  "/logos/Poland - PKO BP Ekstraklasa/Piast Gliwice.png",
  "/logos/Poland - PKO BP Ekstraklasa/Pogon Szczecin.png",
  "/logos/Poland - PKO BP Ekstraklasa/Radomiak Radom.png",
  "/logos/Poland - PKO BP Ekstraklasa/Raków Częstochowa.png",
  "/logos/Poland - PKO BP Ekstraklasa/Slask Wroclaw.png",
  "/logos/Poland - PKO BP Ekstraklasa/Widzew Lodz.png",
  "/logos/Poland - PKO BP Ekstraklasa/Wieczysta Krakow.png",
  "/logos/Poland - PKO BP Ekstraklasa/Wisla Kraków.png",
  "/logos/Poland - PKO BP Ekstraklasa/Wisla Plock.png",
  "/logos/Poland - PKO BP Ekstraklasa/Zaglebie Lubin.png",
  "/logos/Portugal - Liga Portugal/Académico Viseu FC.png",
  "/logos/Portugal - Liga Portugal/Casa Pia AC.png",
  "/logos/Portugal - Liga Portugal/CD Nacional.png",
  "/logos/Portugal - Liga Portugal/CD Santa Clara.png",
  "/logos/Portugal - Liga Portugal/CF Estrela Amadora.png",
  "/logos/Portugal - Liga Portugal/CS Marítimo.png",
  "/logos/Portugal - Liga Portugal/FC Alverca.png",
  "/logos/Portugal - Liga Portugal/FC Arouca.png",
  "/logos/Portugal - Liga Portugal/FC Famalicão.png",
  "/logos/Portugal - Liga Portugal/FC Porto.png",
  "/logos/Portugal - Liga Portugal/GD Estoril Praia.png",
  "/logos/Portugal - Liga Portugal/Gil Vicente FC.png",
  "/logos/Portugal - Liga Portugal/Moreirense FC.png",
  "/logos/Portugal - Liga Portugal/Rio Ave FC.png",
  "/logos/Portugal - Liga Portugal/SC Braga.png",
  "/logos/Portugal - Liga Portugal/SL Benfica.png",
  "/logos/Portugal - Liga Portugal/Sporting CP.png",
  "/logos/Portugal - Liga Portugal/Vitória Guimarães SC.png",
  "/logos/Romania - SuperLiga/ACSC FC Arges.png",
  "/logos/Romania - SuperLiga/CFR Cluj.png",
  "/logos/Romania - SuperLiga/Corvinul Hunedoara.png",
  "/logos/Romania - SuperLiga/FC Botosani.png",
  "/logos/Romania - SuperLiga/FC Dinamo 1948.png",
  "/logos/Romania - SuperLiga/FC Rapid 1923.png",
  "/logos/Romania - SuperLiga/FC Universitatea Cluj.png",
  "/logos/Romania - SuperLiga/FC Voluntari.png",
  "/logos/Romania - SuperLiga/FCSB.png",
  "/logos/Romania - SuperLiga/FCV Farul Constanta.png",
  "/logos/Romania - SuperLiga/FK Csikszereda Miercurea Ciuc.png",
  "/logos/Romania - SuperLiga/Petrolul Ploiesti.png",
  "/logos/Romania - SuperLiga/SC Otelul Galati.png",
  "/logos/Romania - SuperLiga/Sepsi OSK Sf. Gheorghe.png",
  "/logos/Romania - SuperLiga/Universitatea Craiova.png",
  "/logos/Romania - SuperLiga/UTA Arad.png",
  "/logos/Russia - Premier Liga/Akhmat Grozny.png",
  "/logos/Russia - Premier Liga/Akron Tolyatti.png",
  "/logos/Russia - Premier Liga/Baltika Kaliningrad.png",
  "/logos/Russia - Premier Liga/CSKA Moscow.png",
  "/logos/Russia - Premier Liga/Dinamo Makhachkala.png",
  "/logos/Russia - Premier Liga/Dynamo Moscow.png",
  "/logos/Russia - Premier Liga/Fakel Voronezh.png",
  "/logos/Russia - Premier Liga/FC Krasnodar.png",
  "/logos/Russia - Premier Liga/FC Orenburg.png",
  "/logos/Russia - Premier Liga/FC Rostov.png",
  "/logos/Russia - Premier Liga/Krylya Sovetov Samara.png",
  "/logos/Russia - Premier Liga/Lokomotiv Moscow.png",
  "/logos/Russia - Premier Liga/Rodina Moscow.png",
  "/logos/Russia - Premier Liga/Rubin Kazan.png",
  "/logos/Russia - Premier Liga/Spartak Moscow.png",
  "/logos/Russia - Premier Liga/Zenit St. Petersburg.png",
  "/logos/Scotland - Scottish Premiership/Aberdeen FC.png",
  "/logos/Scotland - Scottish Premiership/Celtic FC.png",
  "/logos/Scotland - Scottish Premiership/Dundee FC.png",
  "/logos/Scotland - Scottish Premiership/Dundee United FC.png",
  "/logos/Scotland - Scottish Premiership/Falkirk FC.png",
  "/logos/Scotland - Scottish Premiership/Heart of Midlothian FC.png",
  "/logos/Scotland - Scottish Premiership/Hibernian FC.png",
  "/logos/Scotland - Scottish Premiership/Kilmarnock FC.png",
  "/logos/Scotland - Scottish Premiership/Motherwell FC.png",
  "/logos/Scotland - Scottish Premiership/Rangers FC.png",
  "/logos/Scotland - Scottish Premiership/St. Johnstone FC.png",
  "/logos/Scotland - Scottish Premiership/St. Mirren FC.png",
  "/logos/Serbia - Super liga Srbije/FK Cukaricki.png",
  "/logos/Serbia - Super liga Srbije/FK IMT Belgrad.png",
  "/logos/Serbia - Super liga Srbije/FK Macva Sabac.png",
  "/logos/Serbia - Super liga Srbije/FK Mladost Lucani.png",
  "/logos/Serbia - Super liga Srbije/FK Novi Pazar.png",
  "/logos/Serbia - Super liga Srbije/FK Partizan Belgrade.png",
  "/logos/Serbia - Super liga Srbije/FK Radnicki 1923 Kragujevac.png",
  "/logos/Serbia - Super liga Srbije/FK Radnicki Nis.png",
  "/logos/Serbia - Super liga Srbije/FK Radnik Surdulica.png",
  "/logos/Serbia - Super liga Srbije/FK Vojvodina Novi Sad.png",
  "/logos/Serbia - Super liga Srbije/FK Zeleznicar Pancevo.png",
  "/logos/Serbia - Super liga Srbije/FK Zemun.png",
  "/logos/Serbia - Super liga Srbije/OFK Beograd.png",
  "/logos/Serbia - Super liga Srbije/Red Star Belgrade.png",
  "/logos/Spain - LaLiga/Athletic Bilbao.png",
  "/logos/Spain - LaLiga/Atlético de Madrid.png",
  "/logos/Spain - LaLiga/CA Osasuna.png",
  "/logos/Spain - LaLiga/Celta de Vigo.png",
  "/logos/Spain - LaLiga/Deportivo A Coruña.png",
  "/logos/Spain - LaLiga/Deportivo Alavés.png",
  "/logos/Spain - LaLiga/Elche CF.png",
  "/logos/Spain - LaLiga/FC Barcelona.png",
  "/logos/Spain - LaLiga/Getafe CF.png",
  "/logos/Spain - LaLiga/Levante UD.png",
  "/logos/Spain - LaLiga/Málaga CF.png",
  "/logos/Spain - LaLiga/Racing Santander.png",
  "/logos/Spain - LaLiga/Rayo Vallecano.png",
  "/logos/Spain - LaLiga/RCD Espanyol Barcelona.png",
  "/logos/Spain - LaLiga/Real Betis Balompié.png",
  "/logos/Spain - LaLiga/Real Madrid.png",
  "/logos/Spain - LaLiga/Real Sociedad.png",
  "/logos/Spain - LaLiga/Sevilla FC.png",
  "/logos/Spain - LaLiga/Valencia CF.png",
  "/logos/Spain - LaLiga/Villarreal CF.png",
  "/logos/Sweden - Allsvenskan/AIK.png",
  "/logos/Sweden - Allsvenskan/BK Häcken.png",
  "/logos/Sweden - Allsvenskan/Degerfors IF.png",
  "/logos/Sweden - Allsvenskan/Djurgårdens IF.png",
  "/logos/Sweden - Allsvenskan/GAIS.png",
  "/logos/Sweden - Allsvenskan/Halmstads BK.png",
  "/logos/Sweden - Allsvenskan/Hammarby IF.png",
  "/logos/Sweden - Allsvenskan/IF Brommapojkarna.png",
  "/logos/Sweden - Allsvenskan/IF Elfsborg.png",
  "/logos/Sweden - Allsvenskan/IFK Göteborg.png",
  "/logos/Sweden - Allsvenskan/IK Sirius.png",
  "/logos/Sweden - Allsvenskan/Kalmar FF.png",
  "/logos/Sweden - Allsvenskan/Malmö FF.png",
  "/logos/Sweden - Allsvenskan/Mjällby AIF.png",
  "/logos/Sweden - Allsvenskan/Örgryte IS.png",
  "/logos/Sweden - Allsvenskan/Västerås SK.png",
  "/logos/Switzerland - Super League/BSC Young Boys.png",
  "/logos/Switzerland - Super League/FC Basel 1893.png",
  "/logos/Switzerland - Super League/FC Lausanne-Sport.png",
  "/logos/Switzerland - Super League/FC Lugano.png",
  "/logos/Switzerland - Super League/FC Luzern.png",
  "/logos/Switzerland - Super League/FC Sion.png",
  "/logos/Switzerland - Super League/FC St. Gallen 1879.png",
  "/logos/Switzerland - Super League/FC Thun.png",
  "/logos/Switzerland - Super League/FC Vaduz.png",
  "/logos/Switzerland - Super League/FC Zürich.png",
  "/logos/Switzerland - Super League/Grasshopper Club Zurich.png",
  "/logos/Switzerland - Super League/Servette FC.png",
  "/logos/Türkiye - Süper Lig/Alanyaspor.png",
  "/logos/Türkiye - Süper Lig/Amed SK.png",
  "/logos/Türkiye - Süper Lig/Basaksehir FK.png",
  "/logos/Türkiye - Süper Lig/Besiktas JK.png",
  "/logos/Türkiye - Süper Lig/Caykur Rizespor.png",
  "/logos/Türkiye - Süper Lig/Corum FK.png",
  "/logos/Türkiye - Süper Lig/Erzurum BB.png",
  "/logos/Türkiye - Süper Lig/Eyüpspor.png",
  "/logos/Türkiye - Süper Lig/Fenerbahce.png",
  "/logos/Türkiye - Süper Lig/Galatasaray.png",
  "/logos/Türkiye - Süper Lig/Gaziantep FK.png",
  "/logos/Türkiye - Süper Lig/Genclerbirligi Ankara.png",
  "/logos/Türkiye - Süper Lig/Göztepe.png",
  "/logos/Türkiye - Süper Lig/Kasimpasa.png",
  "/logos/Türkiye - Süper Lig/Kocaelispor.png",
  "/logos/Türkiye - Süper Lig/Konyaspor.png",
  "/logos/Türkiye - Süper Lig/Samsunspor.png",
  "/logos/Türkiye - Süper Lig/Trabzonspor.png",
  "/logos/Ukraine - Premier Liga/Bukovyna Chernivtsi.png",
  "/logos/Ukraine - Premier Liga/Chornomorets Odesa.png",
  "/logos/Ukraine - Premier Liga/Dynamo Kyiv.png",
  "/logos/Ukraine - Premier Liga/Epicentr Kamyanets-Podilskyi.png",
  "/logos/Ukraine - Premier Liga/FC Kharkiv.png",
  "/logos/Ukraine - Premier Liga/FC Kudrivka.png",
  "/logos/Ukraine - Premier Liga/Karpaty Lviv.png",
  "/logos/Ukraine - Premier Liga/Kolos Kovalivka.png",
  "/logos/Ukraine - Premier Liga/Kryvbas Kryvyi Rig.png",
  "/logos/Ukraine - Premier Liga/Livyi Bereg Kyiv.png",
  "/logos/Ukraine - Premier Liga/LNZ Cherkasy.png",
  "/logos/Ukraine - Premier Liga/NK Veres Rivne.png",
  "/logos/Ukraine - Premier Liga/Obolon Kyiv.png",
  "/logos/Ukraine - Premier Liga/Polissya Zhytomyr.png",
  "/logos/Ukraine - Premier Liga/Shakhtar Donetsk.png",
  "/logos/Ukraine - Premier Liga/Zorya Lugansk.png"
];
