// src/data/teamLogos.js
export const teamLogos = {

    //SuperLig Teams
    Besiktas: "/logos/besiktas.webp",
    Fenerbahce: "/logos/fenerbahçe.webp",
    Alanyaspor: "/logos/alanyaspor.webp",
    Galatasaray: "/logos/galatasaray.webp",
    Trabzonspor: "/logos/trabzonspor.webp",
    "Istanbul Basaksehir": "/logos/başakşehir.webp",
    Sivasspor: "/logos/sivasspor.webp",
    Kayserispor: "/logos/kayserispor.webp",
    Antalyaspor: "/logos/antalyaspor.webp",
    AdanaDemirspor: "/logos/adanademirspor.webp",
    Konyaspor: "/logos/konyaspor.webp",
    Giresunspor: "/logos/giresunspor.webp",
    "Caykur Rizespor": "/logos/rizespor.webp",
    Kasimpasa: "/logos/kasımpaşa.webp",
    Ümraniyespor: "/logos/umraniyespor.webp",
    "Fatih Karagümrük": "/logos/fatihkaragumruk.webp",
    Hatayspor: "/logos/hatayspor.webp",
    Denizlispor: "/logos/denizlispor.webp",
    Erzurumspor: "/logos/erzurumspor.webp",
    Sivasspor: "/logos/sivasspor.webp",
    Bursaspor: "/logos/bursaspor.webp",
    Samsunspor: "/logos/samsunspor.webp",
    Alanyaspor: "/logos/alanyaspor.webp",
    Malatyaspor: "/logos/malatyaspor.webp",
    Akhisarspor: "/logos/akhisarspor.webp",
    Kocaelispor: "/logos/kocaeli.webp",
    Eyupspor: "/logos/eyüpspor.webp",
    Genclerbirligi: "/logos/genclerbirliği.webp",
    Goztepe: "/logos/göztepe.webp",
    "Gaziantep FK": "/logos/gaziantep.png",  

    //Serie A Teams
    "Atalanta" : "/logos/atalanta.png",
    "Bologna" : "/logos/bologna.png",
    "Cagliari" : "/logos/cagliari.png",
    "Como" : "/logos/como.png",
    "Cremonese" : "/logos/cremonese.png",
    "Fiorentina" : "/logos/fiorentina.png",
    "Genoa" : "/logos/genoa.png",
    "Hellas Verona" : "/logos/verona.png",
    "Internazionale" : "/logos/inter.png",
    "Juventus" : "/logos/juventus.png",
    "Lazio" : "/logos/lazio.png",
    "Lecce" : "/logos/lecce.png",
    "AC Milan" : "/logos/milan.png",
    "Napoli" : "/logos/napoli.png",
    "Parma" : "/logos/parma.png",
    "Pisa" : "/logos/pisa.png",
    "Sassuolo" : "/logos/sassuolo.png",
    "Torino" : "/logos/torino.png",
    "Udinese" : "/logos/udinese.png",
    "AS Roma" : "/logos/roma.png",

    //premier league teams
    "Arsenal" : "/logos/arsenal.png",
    "Aston Villa" : "/logos/aston_villa.png",
    "AFC Bournemouth" : "/logos/bournemouth.png",
    "Brentford" : "/logos/brentford.png",
    "Brighton & Hove Albion" : "/logos/brighton.png",
    "Burnley" : "/logos/burnley.png",
    "Chelsea" : "/logos/chelsea.png",
    "Crystal Palace" : "/logos/crystal_palace.png",
    "Everton" : "/logos/everton.png",
    "Fulham" : "/logos/fulham.png",
    "Leeds United" : "/logos/leeds.png",
    "Liverpool" : "/logos/liverpool.png",
    "Manchester City" : "/logos/manc.png",
    "Manchester United" : "/logos/manu.png",
    "Newcastle United" : "/logos/newcastle_united.png",
    "Nottingham Forest" : "/logos/nottingham.png",
    "Sunderland" : "/logos/sunderland.png",
    "Tottenham Hotspur" : "/logos/tottenham.png",
    "West Ham United" : "/logos/west_ham_united.png",
    "Wolverhampton Wanderers" : "/logos/wolverhampton.png",

    //bundesliga league teams
    "FC Augsburg" : "/logos/augsburg.png",
    "1. FC Union Berlin" : "/logos/union_berlin.png",
    "Köln" : "/logos/fc_koln.png",
    "Werder Bremen" : "/logos/werder_bremen.png",
    "Borussia Dortmund" : "/logos/borussia_dortmund.png",
    "Eintracht Frankfurt" : "/logos/eintracht_frankfurt.png",
    "SC Freiburg" : "/logos/sc_freiburg.png",
    "1. FC Heidenheim 1846" : "/logos/fc_heidenheim.png",
    "TSG Hoffenheim" : "/logos/tsg_hoffenheim.png",
    "Hamburg SV" : "/logos/hamburg_sv.png",
    "RB Leipzig" : "/logos/rb_leipzig.png",
    "Bayer Leverkusen" : "/logos/bayer_leverkusen.png",
    "Mainz" : "/logos/mainz_05.png",
    "Borussia Mönchengladbach" : "/logos/borussia_monchengladbach.png",
    "St. Pauli" : "/logos/st_pauli.png",
    "VfB Stuttgart" : "/logos/vfb_stuttgart.png",
    "VfL Wolfsburg" : "/logos/vfl_wolfsburg.png",
    "Bayern Munich" : "/logos/bayern_munich.png",

    //LaLiga teams
    "Alavés" : "/logos/alaves.png",
    "Athletic Club" : "/logos/athletic_bilbao.png",
    "Atlético Madrid" : "/logos/atletico_madrid.png",
    "Barcelona" : "/logos/barcelona.png",
    "Celta Vigo" : "/logos/celta_vigo.png",
    "Elche" : "/logos/elche.png",
    "Espanyol" : "/logos/espanyol.png",
    "Getafe" : "/logos/getafe.png",
    "Girona" : "/logos/girona.png",
    "Levante" : "/logos/levante.png",
    "Real Betis" : "/logos/real_betis.png",
    "Real Madrid" : "/logos/real_madrid.png",
    "Real Oviedo" : "/logos/real_oviedo.png",
    "Real Sociedad" : "/logos/real_sociedad.png",
    "Rayo Vallecano" : "/logos/rayo_vallecano.png",
    "Sevilla" : "/logos/sevilla.png",
    "Valencia" : "/logos/valencia.png",
    "Villarreal" : "/logos/villarreal.png",
    "Mallorca" : "/logos/real_mallorca.png",
    "Osasuna" : "/logos/osasuna.png"
};
